### PR TITLE
Start work on number resolver

### PR DESCRIPTION
**Pull request by jujhar16**

### CODE REVIEW

**Review by MathematicalDessert — COMMENTED** [review]
This is a very odd PR. There was no reason to change the CMakeLists.txt nor push CMakeSettings.json. Please check in future! :)

**Review by mathiaslpedersen — DISMISSED** [review]
nope

**Review by MathematicalDessert — DISMISSED** [review]
I agree that some changes need to be made regarding the way that numbers are resolved. This just doesn't make sense and is far too messy. Could you refactor the resolver_visitor and tidy up the visit method for number literals in code_generation.cpp?

**Comment by MathematicalDessert** [comment]
Discard PR.

**Pull request closed without merging**
